widgets:
    -
        type: profile
        position: right
    -
        type: toc
        position: right
        collapsed: true
        depth: 3

    -
        type: categories
        position: right
    # -
    #     type: tags
    #     position: right
   
        