widgets:
    -
        type: toc
        position: right
    -
        type: recent_posts
        position: right
    -
        type: categories
        position: left
    -
        type: tags
        position: left
   
        